server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
#        - id: raffle-service
#          uri: lb://raffle-service
#          predicates:
#            - Path=/raffle/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
