server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      import-check:
        enable: true
      server:
#        native:
#          search-locations: file:./config-repo
        git:
          uri: https://github.com/hyeyeonDev/spring-config-repo
          default-label: main
          search-paths: config

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      process: false
      system: false
